services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_SUPER_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - creator_pg:/var/lib/postgresql
    networks:
      - creator_net

volumes:
  creator_pg:

networks:
  creator_net:
    name: creator_net
