GRANT USAGE ON SCHEMA public TO creator_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO creator_app;
REVOKE UPDATE, DELETE ON TABLE "AuditEvent" FROM creator_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO creator_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO creator_app;
